version: '3.8'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/koes1124/Desktop/MyProjects/LlmModels:/opt/models